#property strict
#property version   "1.01"
#property description "100-strategy MT5 EA - FIXED: Active runs now receive all bars continuously instead of freezing at spawn time"

#include <Trade/Trade.mqh>

CTrade trade;

// ==================== ENUMS ====================
enum ENUM_SIGNAL_DIRECTION { SIGNAL_BUY_ONLY = 0, SIGNAL_SELL_ONLY = 1, SIGNAL_BOTH = 2 };
enum ENUM_LOT_MODE { LOT_RISK_CURRENT_BALANCE = 0, LOT_RISK_STARTING_BALANCE = 1, LOT_FIXED = 2 };
enum ENUM_STOP_MODE { STOP_ATR_MULTIPLIER = 0, STOP_FIXED_POINTS = 1, STOP_FIXED_MONEY = 2 };
enum ENUM_STRATEGY_MODE { STRATEGY_ALL = 0, STRATEGY_SINGLE = 1 };
enum ENUM_PROP_STRATEGY_MODE { PROP_STRATEGY_ALL = 0, PROP_STRATEGY_CUSTOM = 1 };

// ==================== ACTIVE RUN STATE STRUCT ====================
struct RunState
{
   datetime startTime;           // When this run spawned
   datetime lastProcessedBar;    // Last bar time processed ← KEY FIX
   int tradeCount;              // Cumulative trades
   int signalCount;             // Cumulative signals
   double startBalance;         // Initial balance for this run
   double currentBalance;       // Current equity
   double maxProfit;            // Highest equity reach
   double maxDrawdown;          // Largest loss from start
   bool isActive;               // Still trading?
   string status;               // ACTIVE, PASSED, BLOWN
};

// ==================== GLOBAL RUN TRACKING ====================
RunState activeRuns[10000];      // Support up to 10k concurrent runs
int totalRuns = 0;
static datetime lastBarProcessed = 0;  // ← KEY FIX: Ensure once-per-bar execution

// ==================== INPUT PARAMETERS ====================
input ENUM_NAMED_STRATEGY   selectedStrategy = STRAT_799_ADX_RSI_POSITION;
input ENUM_STRATEGY_MODE    strategyMode = STRATEGY_SINGLE;
input ENUM_PROP_STRATEGY_MODE propMode = PROP_STRATEGY_CUSTOM;
input int spawnIntervalMinutes = 15;
input int maxSpawnBatches = 0;  // 0 = unlimited
input double startingBalance = 5000.0;
input double profitTarget = 250.0;       // 5% of 5000
input double maxTotalDrawdown = 250.0;   // 5% max loss
input double maxDailyDrawdown = 200.0;   // 4% daily loss
input double virtualTakeProfit = 200.0;  // Per trade TP
input double virtualStopLoss = 100.0;    // Per trade SL
input double fixedLotSize = 0.10;
input bool oneTradePerBar = true;
input bool reverseSignals = false;

// ==================== STRATEGY ENUM (ALL 1000) ====================
enum ENUM_NAMED_STRATEGY
{
   STRAT_001_EMA_SCALP_CROSS = 1, STRAT_002_EMA_FAST_PULLBACK, STRAT_003_EMA_SWING_CROSS,
   STRAT_004_EMA_TREND_RIDER, STRAT_005_EMA_MOMENTUM_SHIFT, STRAT_006_EMA_DEEP_PULLBACK,
   STRAT_007_EMA_SESSION_TREND, STRAT_008_EMA_BREAK_TREND, STRAT_009_EMA_POSITION_SWING,
   STRAT_010_EMA_MAJOR_TREND, STRAT_011_RSI_SNAPBACK_FAST, STRAT_012_RSI_OVERSOLD_RECOVERY,
   STRAT_013_RSI_BALANCE_REVERSION, STRAT_014_RSI_SWING_REBOUND, STRAT_015_RSI_TREND_REENTRY,
   STRAT_016_RSI_DEEP_REVERSAL, STRAT_017_RSI_SOFT_EXTREME, STRAT_018_RSI_SHARP_EXTREME,
   STRAT_019_RSI_RANGE_FADE, STRAT_020_RSI_EXHAUSTION_TURN,
   STRAT_021_BREAKOUT_MICRO_RANGE, STRAT_022_BREAKOUT_SHORT_RANGE, STRAT_023_BREAKOUT_INTRADAY_RANGE,
   STRAT_024_BREAKOUT_SWING_RANGE, STRAT_025_BREAKOUT_EXPANSION, STRAT_026_BREAKOUT_TREND_CONTINUE,
   STRAT_027_BREAKOUT_VOLATILITY_PUSH, STRAT_028_BREAKOUT_STRUCTURE_BREAK, STRAT_029_BREAKOUT_POSITION_RANGE,
   STRAT_030_BREAKOUT_MAJOR_RANGE,
   STRAT_031_BB_LOWER_RECLAIM, STRAT_032_BB_MEAN_REVERSION, STRAT_033_BB_VOLATILITY_FADE,
   STRAT_034_BB_SWING_REVERT, STRAT_035_BB_BALANCED_BOUNCE, STRAT_036_BB_DEEP_BAND_REJECT,
   STRAT_037_BB_SOFT_BAND_REJECT, STRAT_038_BB_TREND_PULLBACK, STRAT_039_BB_POSITION_BOUNCE,
   STRAT_040_BB_EXTREME_REVERSION,
   STRAT_041_MACD_FAST_FLIP, STRAT_042_MACD_SCALP_CROSS, STRAT_043_MACD_TREND_SHIFT,
   STRAT_044_MACD_SWING_CROSS, STRAT_045_MACD_MOMENTUM_BUILD, STRAT_046_MACD_DEEP_TREND,
   STRAT_047_MACD_BALANCED_SIGNAL, STRAT_048_MACD_SLOW_REVERSAL, STRAT_049_MACD_POSITION_SHIFT,
   STRAT_050_MACD_MAJOR_CYCLE,
   STRAT_051_STOCH_FAST_TURN, STRAT_052_STOCH_OVERSOLD_CROSS, STRAT_053_STOCH_RANGE_RECOVERY,
   STRAT_054_STOCH_SWING_TURN, STRAT_055_STOCH_TREND_REENTRY, STRAT_056_STOCH_DEEP_CYCLE,
   STRAT_057_STOCH_SOFT_REVERSAL, STRAT_058_STOCH_SHARP_REVERSAL, STRAT_059_STOCH_POSITION_CYCLE,
   STRAT_060_STOCH_MAJOR_TURN,
   STRAT_061_CCI_FAST_RECLAIM, STRAT_062_CCI_OVERSOLD_REBOUND, STRAT_063_CCI_RANGE_REVERSION,
   STRAT_064_CCI_SWING_RECLAIM, STRAT_065_CCI_TREND_REENTRY, STRAT_066_CCI_DEEP_EXTREME,
   STRAT_067_CCI_SOFT_EXTREME, STRAT_068_CCI_SHARP_EXTREME, STRAT_069_CCI_POSITION_REVERT,
   STRAT_070_CCI_MAJOR_REVERSAL,
   STRAT_071_MOMENTUM_FAST_PUSH, STRAT_072_MOMENTUM_SCALP_BURST, STRAT_073_MOMENTUM_TREND_CONFIRM,
   STRAT_074_MOMENTUM_SWING_PUSH, STRAT_075_MOMENTUM_EXPANSION, STRAT_076_MOMENTUM_CONTINUATION,
   STRAT_077_MOMENTUM_VOLATILITY_BURST, STRAT_078_MOMENTUM_STRUCTURE_PUSH, STRAT_079_MOMENTUM_POSITION_PUSH,
   STRAT_080_MOMENTUM_MAJOR_PUSH,
   STRAT_081_ATR_CHANNEL_FAST_BREAK, STRAT_082_ATR_CHANNEL_SCALP_BREAK, STRAT_083_ATR_CHANNEL_TREND_BREAK,
   STRAT_084_ATR_CHANNEL_SWING_BREAK, STRAT_085_ATR_CHANNEL_EXPANSION, STRAT_086_ATR_CHANNEL_CONTINUE,
   STRAT_087_ATR_CHANNEL_VOLATILE, STRAT_088_ATR_CHANNEL_STRUCTURE, STRAT_089_ATR_CHANNEL_POSITION,
   STRAT_090_ATR_CHANNEL_MAJOR,
   STRAT_091_PRICE_ACTION_MICRO_ENGULF, STRAT_092_PRICE_ACTION_SHORT_BREAK, STRAT_093_PRICE_ACTION_INTRADAY_PUSH,
   STRAT_094_PRICE_ACTION_SWING_CANDLE, STRAT_095_PRICE_ACTION_RANGE_BREAK, STRAT_096_PRICE_ACTION_TREND_CANDLE,
   STRAT_097_PRICE_ACTION_VOLATILE_BAR, STRAT_098_PRICE_ACTION_STRUCTURE_BAR, STRAT_099_PRICE_ACTION_POSITION_BAR,
   STRAT_100_PRICE_ACTION_MAJOR_BAR,
   STRAT_101_EMA_SLOPE_MICRO, STRAT_102_EMA_SLOPE_FAST, STRAT_103_EMA_SLOPE_SHORT,
   STRAT_104_EMA_SLOPE_INTRADAY, STRAT_105_EMA_SLOPE_SWING, STRAT_106_EMA_SLOPE_EXPANSION,
   STRAT_107_EMA_SLOPE_CONTINUE, STRAT_108_EMA_SLOPE_VOLATILE, STRAT_109_EMA_SLOPE_POSITION,
   STRAT_110_EMA_SLOPE_MAJOR,
   STRAT_111_EMA_XFILT_MICRO, STRAT_112_EMA_XFILT_FAST, STRAT_113_EMA_XFILT_SHORT,
   STRAT_114_EMA_XFILT_INTRADAY, STRAT_115_EMA_XFILT_SWING, STRAT_116_EMA_XFILT_EXPANSION,
   STRAT_117_EMA_XFILT_CONTINUE, STRAT_118_EMA_XFILT_VOLATILE, STRAT_119_EMA_XFILT_POSITION,
   STRAT_120_EMA_XFILT_MAJOR,
   STRAT_121_EMA_RIBBON_MICRO, STRAT_122_EMA_RIBBON_FAST, STRAT_123_EMA_RIBBON_SHORT,
   STRAT_124_EMA_RIBBON_INTRADAY, STRAT_125_EMA_RIBBON_SWING, STRAT_126_EMA_RIBBON_EXPANSION,
   STRAT_127_EMA_RIBBON_CONTINUE, STRAT_128_EMA_RIBBON_VOLATILE, STRAT_129_EMA_RIBBON_POSITION,
   STRAT_130_EMA_RIBBON_MAJOR,
   STRAT_131_ENVELOPE_MICRO, STRAT_132_ENVELOPE_FAST, STRAT_133_ENVELOPE_SHORT,
   STRAT_134_ENVELOPE_INTRADAY, STRAT_135_ENVELOPE_SWING, STRAT_136_ENVELOPE_EXPANSION,
   STRAT_137_ENVELOPE_CONTINUE, STRAT_138_ENVELOPE_VOLATILE, STRAT_139_ENVELOPE_POSITION,
   STRAT_140_ENVELOPE_MAJOR,
   STRAT_141_ALLIGATOR_MICRO, STRAT_142_ALLIGATOR_FAST, STRAT_143_ALLIGATOR_SHORT,
   STRAT_144_ALLIGATOR_INTRADAY, STRAT_145_ALLIGATOR_SWING, STRAT_146_ALLIGATOR_EXPANSION,
   STRAT_147_ALLIGATOR_CONTINUE, STRAT_148_ALLIGATOR_VOLATILE, STRAT_149_ALLIGATOR_POSITION,
   STRAT_150_ALLIGATOR_MAJOR,
   STRAT_151_RSI_MID_MICRO, STRAT_152_RSI_MID_FAST, STRAT_153_RSI_MID_SHORT,
   STRAT_154_RSI_MID_INTRADAY, STRAT_155_RSI_MID_SWING, STRAT_156_RSI_MID_EXPANSION,
   STRAT_157_RSI_MID_CONTINUE, STRAT_158_RSI_MID_VOLATILE, STRAT_159_RSI_MID_POSITION,
   STRAT_160_RSI_MID_MAJOR,
   STRAT_161_RSI_EXTR_MICRO, STRAT_162_RSI_EXTR_FAST, STRAT_163_RSI_EXTR_SHORT,
   STRAT_164_RSI_EXTR_INTRADAY, STRAT_165_RSI_EXTR_SWING, STRAT_166_RSI_EXTR_EXPANSION,
   STRAT_167_RSI_EXTR_CONTINUE, STRAT_168_RSI_EXTR_VOLATILE, STRAT_169_RSI_EXTR_POSITION,
   STRAT_170_RSI_EXTR_MAJOR,
   STRAT_171_RSI_TRND_MICRO, STRAT_172_RSI_TRND_FAST, STRAT_173_RSI_TRND_SHORT,
   STRAT_174_RSI_TRND_INTRADAY, STRAT_175_RSI_TRND_SWING, STRAT_176_RSI_TRND_EXPANSION,
   STRAT_177_RSI_TRND_CONTINUE, STRAT_178_RSI_TRND_VOLATILE, STRAT_179_RSI_TRND_POSITION,
   STRAT_180_RSI_TRND_MAJOR,
   STRAT_181_RVI_MICRO, STRAT_182_RVI_FAST, STRAT_183_RVI_SHORT,
   STRAT_184_RVI_INTRADAY, STRAT_185_RVI_SWING, STRAT_186_RVI_EXPANSION,
   STRAT_187_RVI_CONTINUE, STRAT_188_RVI_VOLATILE, STRAT_189_RVI_POSITION,
   STRAT_190_RVI_MAJOR,
   STRAT_191_DEMARKER_MICRO, STRAT_192_DEMARKER_FAST, STRAT_193_DEMARKER_SHORT,
   STRAT_194_DEMARKER_INTRADAY, STRAT_195_DEMARKER_SWING, STRAT_196_DEMARKER_EXPANSION,
   STRAT_197_DEMARKER_CONTINUE, STRAT_198_DEMARKER_VOLATILE, STRAT_199_DEMARKER_POSITION,
   STRAT_200_DEMARKER_MAJOR,
   STRAT_201_MACD_ZERO_MICRO, STRAT_202_MACD_ZERO_FAST, STRAT_203_MACD_ZERO_SHORT,
   STRAT_204_MACD_ZERO_INTRADAY, STRAT_205_MACD_ZERO_SWING, STRAT_206_MACD_ZERO_EXPANSION,
   STRAT_207_MACD_ZERO_CONTINUE, STRAT_208_MACD_ZERO_VOLATILE, STRAT_209_MACD_ZERO_POSITION,
   STRAT_210_MACD_ZERO_MAJOR,
   STRAT_211_MACD_HIST_MICRO, STRAT_212_MACD_HIST_FAST, STRAT_213_MACD_HIST_SHORT,
   STRAT_214_MACD_HIST_INTRADAY, STRAT_215_MACD_HIST_SWING, STRAT_216_MACD_HIST_EXPANSION,
   STRAT_217_MACD_HIST_CONTINUE, STRAT_218_MACD_HIST_VOLATILE, STRAT_219_MACD_HIST_POSITION,
   STRAT_220_MACD_HIST_MAJOR,
   STRAT_221_OSMA_MICRO, STRAT_222_OSMA_FAST, STRAT_223_OSMA_SHORT,
   STRAT_224_OSMA_INTRADAY, STRAT_225_OSMA_SWING, STRAT_226_OSMA_EXPANSION,
   STRAT_227_OSMA_CONTINUE, STRAT_228_OSMA_VOLATILE, STRAT_229_OSMA_POSITION,
   STRAT_230_OSMA_MAJOR,
   STRAT_231_STOCH_RSI_MICRO, STRAT_232_STOCH_RSI_FAST, STRAT_233_STOCH_RSI_SHORT,
   STRAT_234_STOCH_RSI_INTRADAY, STRAT_235_STOCH_RSI_SWING, STRAT_236_STOCH_RSI_EXPANSION,
   STRAT_237_STOCH_RSI_CONTINUE, STRAT_238_STOCH_RSI_VOLATILE, STRAT_239_STOCH_RSI_POSITION,
   STRAT_240_STOCH_RSI_MAJOR,
   STRAT_241_WILLIAMS_MICRO, STRAT_242_WILLIAMS_FAST, STRAT_243_WILLIAMS_SHORT,
   STRAT_244_WILLIAMS_INTRADAY, STRAT_245_WILLIAMS_SWING, STRAT_246_WILLIAMS_EXPANSION,
   STRAT_247_WILLIAMS_CONTINUE, STRAT_248_WILLIAMS_VOLATILE, STRAT_249_WILLIAMS_POSITION,
   STRAT_250_WILLIAMS_MAJOR,
   STRAT_251_DONCHIAN_MICRO, STRAT_252_DONCHIAN_FAST, STRAT_253_DONCHIAN_SHORT,
   STRAT_254_DONCHIAN_INTRADAY, STRAT_255_DONCHIAN_SWING, STRAT_256_DONCHIAN_EXPANSION,
   STRAT_257_DONCHIAN_CONTINUE, STRAT_258_DONCHIAN_VOLATILE, STRAT_259_DONCHIAN_POSITION,
   STRAT_260_DONCHIAN_MAJOR,
   STRAT_261_BB_SQUEEZE_MICRO, STRAT_262_BB_SQUEEZE_FAST, STRAT_263_BB_SQUEEZE_SHORT,
   STRAT_264_BB_SQUEEZE_INTRADAY, STRAT_265_BB_SQUEEZE_SWING, STRAT_266_BB_SQUEEZE_EXPANSION,
   STRAT_267_BB_SQUEEZE_CONTINUE, STRAT_268_BB_SQUEEZE_VOLATILE, STRAT_269_BB_SQUEEZE_POSITION,
   STRAT_270_BB_SQUEEZE_MAJOR,
   STRAT_271_KELTNER_MICRO, STRAT_272_KELTNER_FAST, STRAT_273_KELTNER_SHORT,
   STRAT_274_KELTNER_INTRADAY, STRAT_275_KELTNER_SWING, STRAT_276_KELTNER_EXPANSION,
   STRAT_277_KELTNER_CONTINUE, STRAT_278_KELTNER_VOLATILE, STRAT_279_KELTNER_POSITION,
   STRAT_280_KELTNER_MAJOR,
   STRAT_281_BB_WALK_MICRO, STRAT_282_BB_WALK_FAST, STRAT_283_BB_WALK_SHORT,
   STRAT_284_BB_WALK_INTRADAY, STRAT_285_BB_WALK_SWING, STRAT_286_BB_WALK_EXPANSION,
   STRAT_287_BB_WALK_CONTINUE, STRAT_288_BB_WALK_VOLATILE, STRAT_289_BB_WALK_POSITION,
   STRAT_290_BB_WALK_MAJOR,
   STRAT_291_ENV_REVERT_MICRO, STRAT_292_ENV_REVERT_FAST, STRAT_293_ENV_REVERT_SHORT,
   STRAT_294_ENV_REVERT_INTRADAY, STRAT_295_ENV_REVERT_SWING, STRAT_296_ENV_REVERT_EXPANSION,
   STRAT_297_ENV_REVERT_CONTINUE, STRAT_298_ENV_REVERT_VOLATILE, STRAT_299_ENV_REVERT_POSITION,
   STRAT_300_ENV_REVERT_MAJOR,
   STRAT_301_ADX_TREND_MICRO, STRAT_302_ADX_TREND_FAST, STRAT_303_ADX_TREND_SHORT,
   STRAT_304_ADX_TREND_INTRADAY, STRAT_305_ADX_TREND_SWING, STRAT_306_ADX_TREND_EXPANSION,
   STRAT_307_ADX_TREND_CONTINUE, STRAT_308_ADX_TREND_VOLATILE, STRAT_309_ADX_TREND_POSITION,
   STRAT_310_ADX_TREND_MAJOR,
   STRAT_311_SAR_FLIP_MICRO, STRAT_312_SAR_FLIP_FAST, STRAT_313_SAR_FLIP_SHORT,
   STRAT_314_SAR_FLIP_INTRADAY, STRAT_315_SAR_FLIP_SWING, STRAT_316_SAR_FLIP_EXPANSION,
   STRAT_317_SAR_FLIP_CONTINUE, STRAT_318_SAR_FLIP_VOLATILE, STRAT_319_SAR_FLIP_POSITION,
   STRAT_320_SAR_FLIP_MAJOR,
   STRAT_321_SUPERTREND_MICRO, STRAT_322_SUPERTREND_FAST, STRAT_323_SUPERTREND_SHORT,
   STRAT_324_SUPERTREND_INTRADAY, STRAT_325_SUPERTREND_SWING, STRAT_326_SUPERTREND_EXPANSION,
   STRAT_327_SUPERTREND_CONTINUE, STRAT_328_SUPERTREND_VOLATILE, STRAT_329_SUPERTREND_POSITION,
   STRAT_330_SUPERTREND_MAJOR,
   STRAT_331_CCI_TRND_MICRO, STRAT_332_CCI_TRND_FAST, STRAT_333_CCI_TRND_SHORT,
   STRAT_334_CCI_TRND_INTRADAY, STRAT_335_CCI_TRND_SWING, STRAT_336_CCI_TRND_EXPANSION,
   STRAT_337_CCI_TRND_CONTINUE, STRAT_338_CCI_TRND_VOLATILE, STRAT_339_CCI_TRND_POSITION,
   STRAT_340_CCI_TRND_MAJOR,
   STRAT_341_CCI_EXTR_MICRO, STRAT_342_CCI_EXTR_FAST, STRAT_343_CCI_EXTR_SHORT,
   STRAT_344_CCI_EXTR_INTRADAY, STRAT_345_CCI_EXTR_SWING, STRAT_346_CCI_EXTR_EXPANSION,
   STRAT_347_CCI_EXTR_CONTINUE, STRAT_348_CCI_EXTR_VOLATILE, STRAT_349_CCI_EXTR_POSITION,
   STRAT_350_CCI_EXTR_MAJOR,
   STRAT_351_MFI_MICRO, STRAT_352_MFI_FAST, STRAT_353_MFI_SHORT,
   STRAT_354_MFI_INTRADAY, STRAT_355_MFI_SWING, STRAT_356_MFI_EXPANSION,
   STRAT_357_MFI_CONTINUE, STRAT_358_MFI_VOLATILE, STRAT_359_MFI_POSITION,
   STRAT_360_MFI_MAJOR,
   STRAT_361_OBV_TREND_MICRO, STRAT_362_OBV_TREND_FAST, STRAT_363_OBV_TREND_SHORT,
   STRAT_364_OBV_TREND_INTRADAY, STRAT_365_OBV_TREND_SWING, STRAT_366_OBV_TREND_EXPANSION,
   STRAT_367_OBV_TREND_CONTINUE, STRAT_368_OBV_TREND_VOLATILE, STRAT_369_OBV_TREND_POSITION,
   STRAT_370_OBV_TREND_MAJOR,
   STRAT_371_FORCE_MICRO, STRAT_372_FORCE_FAST, STRAT_373_FORCE_SHORT,
   STRAT_374_FORCE_INTRADAY, STRAT_375_FORCE_SWING, STRAT_376_FORCE_EXPANSION,
   STRAT_377_FORCE_CONTINUE, STRAT_378_FORCE_VOLATILE, STRAT_379_FORCE_POSITION,
   STRAT_380_FORCE_MAJOR,
   STRAT_381_VOL_BREAK_MICRO, STRAT_382_VOL_BREAK_FAST, STRAT_383_VOL_BREAK_SHORT,
   STRAT_384_VOL_BREAK_INTRADAY, STRAT_385_VOL_BREAK_SWING, STRAT_386_VOL_BREAK_EXPANSION,
   STRAT_387_VOL_BREAK_CONTINUE, STRAT_388_VOL_BREAK_VOLATILE, STRAT_389_VOL_BREAK_POSITION,
   STRAT_390_VOL_BREAK_MAJOR,
   STRAT_391_ACCELERATOR_MICRO, STRAT_392_ACCELERATOR_FAST, STRAT_393_ACCELERATOR_SHORT,
   STRAT_394_ACCELERATOR_INTRADAY, STRAT_395_ACCELERATOR_SWING, STRAT_396_ACCELERATOR_EXPANSION,
   STRAT_397_ACCELERATOR_CONTINUE, STRAT_398_ACCELERATOR_VOLATILE, STRAT_399_ACCELERATOR_POSITION,
   STRAT_400_ACCELERATOR_MAJOR,
   STRAT_401_ENGULFING_MICRO, STRAT_402_ENGULFING_FAST, STRAT_403_ENGULFING_SHORT,
   STRAT_404_ENGULFING_INTRADAY, STRAT_405_ENGULFING_SWING, STRAT_406_ENGULFING_EXPANSION,
   STRAT_407_ENGULFING_CONTINUE, STRAT_408_ENGULFING_VOLATILE, STRAT_409_ENGULFING_POSITION,
   STRAT_410_ENGULFING_MAJOR,
   STRAT_411_PIN_BAR_MICRO, STRAT_412_PIN_BAR_FAST, STRAT_413_PIN_BAR_SHORT,
   STRAT_414_PIN_BAR_INTRADAY, STRAT_415_PIN_BAR_SWING, STRAT_416_PIN_BAR_EXPANSION,
   STRAT_417_PIN_BAR_CONTINUE, STRAT_418_PIN_BAR_VOLATILE, STRAT_419_PIN_BAR_POSITION,
   STRAT_420_PIN_BAR_MAJOR,
   STRAT_421_INSIDE_BAR_MICRO, STRAT_422_INSIDE_BAR_FAST, STRAT_423_INSIDE_BAR_SHORT,
   STRAT_424_INSIDE_BAR_INTRADAY, STRAT_425_INSIDE_BAR_SWING, STRAT_426_INSIDE_BAR_EXPANSION,
   STRAT_427_INSIDE_BAR_CONTINUE, STRAT_428_INSIDE_BAR_VOLATILE, STRAT_429_INSIDE_BAR_POSITION,
   STRAT_430_INSIDE_BAR_MAJOR,
   STRAT_431_THREE_BAR_MICRO, STRAT_432_THREE_BAR_FAST, STRAT_433_THREE_BAR_SHORT,
   STRAT_434_THREE_BAR_INTRADAY, STRAT_435_THREE_BAR_SWING, STRAT_436_THREE_BAR_EXPANSION,
   STRAT_437_THREE_BAR_CONTINUE, STRAT_438_THREE_BAR_VOLATILE, STRAT_439_THREE_BAR_POSITION,
   STRAT_440_THREE_BAR_MAJOR,
   STRAT_441_KEY_LEVEL_MICRO, STRAT_442_KEY_LEVEL_FAST, STRAT_443_KEY_LEVEL_SHORT,
   STRAT_444_KEY_LEVEL_INTRADAY, STRAT_445_KEY_LEVEL_SWING, STRAT_446_KEY_LEVEL_EXPANSION,
   STRAT_447_KEY_LEVEL_CONTINUE, STRAT_448_KEY_LEVEL_VOLATILE, STRAT_449_KEY_LEVEL_POSITION,
   STRAT_450_KEY_LEVEL_MAJOR,
   STRAT_451_EMA_RSI_MICRO, STRAT_452_EMA_RSI_FAST, STRAT_453_EMA_RSI_SHORT,
   STRAT_454_EMA_RSI_INTRADAY, STRAT_455_EMA_RSI_SWING, STRAT_456_EMA_RSI_EXPANSION,
   STRAT_457_EMA_RSI_CONTINUE, STRAT_458_EMA_RSI_VOLATILE, STRAT_459_EMA_RSI_POSITION,
   STRAT_460_EMA_RSI_MAJOR,
   STRAT_461_MACD_BANDS_MICRO, STRAT_462_MACD_BANDS_FAST, STRAT_463_MACD_BANDS_SHORT,
   STRAT_464_MACD_BANDS_INTRADAY, STRAT_465_MACD_BANDS_SWING, STRAT_466_MACD_BANDS_EXPANSION,
   STRAT_467_MACD_BANDS_CONTINUE, STRAT_468_MACD_BANDS_VOLATILE, STRAT_469_MACD_BANDS_POSITION,
   STRAT_470_MACD_BANDS_MAJOR,
   STRAT_471_STOCH_ADX_MICRO, STRAT_472_STOCH_ADX_FAST, STRAT_473_STOCH_ADX_SHORT,
   STRAT_474_STOCH_ADX_INTRADAY, STRAT_475_STOCH_ADX_SWING, STRAT_476_STOCH_ADX_EXPANSION,
   STRAT_477_STOCH_ADX_CONTINUE, STRAT_478_STOCH_ADX_VOLATILE, STRAT_479_STOCH_ADX_POSITION,
   STRAT_480_STOCH_ADX_MAJOR,
   STRAT_481_ATR_BREAK_MICRO, STRAT_482_ATR_BREAK_FAST, STRAT_483_ATR_BREAK_SHORT,
   STRAT_484_ATR_BREAK_INTRADAY, STRAT_485_ATR_BREAK_SWING, STRAT_486_ATR_BREAK_EXPANSION,
   STRAT_487_ATR_BREAK_CONTINUE, STRAT_488_ATR_BREAK_VOLATILE, STRAT_489_ATR_BREAK_POSITION,
   STRAT_490_ATR_BREAK_MAJOR,
   STRAT_491_TREND_MOM_MICRO, STRAT_492_TREND_MOM_FAST, STRAT_493_TREND_MOM_SHORT,
   STRAT_494_TREND_MOM_INTRADAY, STRAT_495_TREND_MOM_SWING, STRAT_496_TREND_MOM_EXPANSION,
   STRAT_497_TREND_MOM_CONTINUE, STRAT_498_TREND_MOM_VOLATILE, STRAT_499_TREND_MOM_POSITION,
   STRAT_500_TREND_MOM_MAJOR,
   STRAT_501_ICHIMOKU_MICRO, STRAT_502_ICHIMOKU_FAST, STRAT_503_ICHIMOKU_SHORT,
   STRAT_504_ICHIMOKU_INTRADAY, STRAT_505_ICHIMOKU_SWING, STRAT_506_ICHIMOKU_EXPANSION,
   STRAT_507_ICHIMOKU_CONTINUE, STRAT_508_ICHIMOKU_VOLATILE, STRAT_509_ICHIMOKU_POSITION,
   STRAT_510_ICHIMOKU_MAJOR,
   STRAT_511_CHAIKIN_MICRO, STRAT_512_CHAIKIN_FAST, STRAT_513_CHAIKIN_SHORT,
   STRAT_514_CHAIKIN_INTRADAY, STRAT_515_CHAIKIN_SWING, STRAT_516_CHAIKIN_EXPANSION,
   STRAT_517_CHAIKIN_CONTINUE, STRAT_518_CHAIKIN_VOLATILE, STRAT_519_CHAIKIN_POSITION,
   STRAT_520_CHAIKIN_MAJOR,
   STRAT_521_GATOR_MICRO, STRAT_522_GATOR_FAST, STRAT_523_GATOR_SHORT,
   STRAT_524_GATOR_INTRADAY, STRAT_525_GATOR_SWING, STRAT_526_GATOR_EXPANSION,
   STRAT_527_GATOR_CONTINUE, STRAT_528_GATOR_VOLATILE, STRAT_529_GATOR_POSITION,
   STRAT_530_GATOR_MAJOR,
   STRAT_531_FRACTAL_MICRO, STRAT_532_FRACTAL_FAST, STRAT_533_FRACTAL_SHORT,
   STRAT_534_FRACTAL_INTRADAY, STRAT_535_FRACTAL_SWING, STRAT_536_FRACTAL_EXPANSION,
   STRAT_537_FRACTAL_CONTINUE, STRAT_538_FRACTAL_VOLATILE, STRAT_539_FRACTAL_POSITION,
   STRAT_540_FRACTAL_MAJOR,
   STRAT_541_STDDEV_CHANNEL_MICRO, STRAT_542_STDDEV_CHANNEL_FAST, STRAT_543_STDDEV_CHANNEL_SHORT,
   STRAT_544_STDDEV_CHANNEL_INTRADAY, STRAT_545_STDDEV_CHANNEL_SWING, STRAT_546_STDDEV_CHANNEL_EXPANSION,
   STRAT_547_STDDEV_CHANNEL_CONTINUE, STRAT_548_STDDEV_CHANNEL_VOLATILE, STRAT_549_STDDEV_CHANNEL_POSITION,
   STRAT_550_STDDEV_CHANNEL_MAJOR,
   STRAT_551_BULLS_POWER_MICRO, STRAT_552_BULLS_POWER_FAST, STRAT_553_BULLS_POWER_SHORT,
   STRAT_554_BULLS_POWER_INTRADAY, STRAT_555_BULLS_POWER_SWING, STRAT_556_BULLS_POWER_EXPANSION,
   STRAT_557_BULLS_POWER_CONTINUE, STRAT_558_BULLS_POWER_VOLATILE, STRAT_559_BULLS_POWER_POSITION,
   STRAT_560_BULLS_POWER_MAJOR,
   STRAT_561_BEARS_POWER_MICRO, STRAT_562_BEARS_POWER_FAST, STRAT_563_BEARS_POWER_SHORT,
   STRAT_564_BEARS_POWER_INTRADAY, STRAT_565_BEARS_POWER_SWING, STRAT_566_BEARS_POWER_EXPANSION,
   STRAT_567_BEARS_POWER_CONTINUE, STRAT_568_BEARS_POWER_VOLATILE, STRAT_569_BEARS_POWER_POSITION,
   STRAT_570_BEARS_POWER_MAJOR,
   STRAT_571_CMO_MICRO, STRAT_572_CMO_FAST, STRAT_573_CMO_SHORT,
   STRAT_574_CMO_INTRADAY, STRAT_575_CMO_SWING, STRAT_576_CMO_EXPANSION,
   STRAT_577_CMO_CONTINUE, STRAT_578_CMO_VOLATILE, STRAT_579_CMO_POSITION,
   STRAT_580_CMO_MAJOR,
   STRAT_581_TEMA_MICRO, STRAT_582_TEMA_FAST, STRAT_583_TEMA_SHORT,
   STRAT_584_TEMA_INTRADAY, STRAT_585_TEMA_SWING, STRAT_586_TEMA_EXPANSION,
   STRAT_587_TEMA_CONTINUE, STRAT_588_TEMA_VOLATILE, STRAT_589_TEMA_POSITION,
   STRAT_590_TEMA_MAJOR,
   STRAT_591_TRIX_MICRO, STRAT_592_TRIX_FAST, STRAT_593_TRIX_SHORT,
   STRAT_594_TRIX_INTRADAY, STRAT_595_TRIX_SWING, STRAT_596_TRIX_EXPANSION,
   STRAT_597_TRIX_CONTINUE, STRAT_598_TRIX_VOLATILE, STRAT_599_TRIX_POSITION,
   STRAT_600_TRIX_MAJOR,
   STRAT_601_VIDYA_MICRO, STRAT_602_VIDYA_FAST, STRAT_603_VIDYA_SHORT,
   STRAT_604_VIDYA_INTRADAY, STRAT_605_VIDYA_SWING, STRAT_606_VIDYA_EXPANSION,
   STRAT_607_VIDYA_CONTINUE, STRAT_608_VIDYA_VOLATILE, STRAT_609_VIDYA_POSITION,
   STRAT_610_VIDYA_MAJOR,
   STRAT_611_FRAMA_MICRO, STRAT_612_FRAMA_FAST, STRAT_613_FRAMA_SHORT,
   STRAT_614_FRAMA_INTRADAY, STRAT_615_FRAMA_SWING, STRAT_616_FRAMA_EXPANSION,
   STRAT_617_FRAMA_CONTINUE, STRAT_618_FRAMA_VOLATILE, STRAT_619_FRAMA_POSITION,
   STRAT_620_FRAMA_MAJOR,
   STRAT_621_ULTIMATE_OSC_MICRO, STRAT_622_ULTIMATE_OSC_FAST, STRAT_623_ULTIMATE_OSC_SHORT,
   STRAT_624_ULTIMATE_OSC_INTRADAY, STRAT_625_ULTIMATE_OSC_SWING, STRAT_626_ULTIMATE_OSC_EXPANSION,
   STRAT_627_ULTIMATE_OSC_CONTINUE, STRAT_628_ULTIMATE_OSC_VOLATILE, STRAT_629_ULTIMATE_OSC_POSITION,
   STRAT_630_ULTIMATE_OSC_MAJOR,
   STRAT_631_HEIKEN_ASHI_MICRO, STRAT_632_HEIKEN_ASHI_FAST, STRAT_633_HEIKEN_ASHI_SHORT,
   STRAT_634_HEIKEN_ASHI_INTRADAY, STRAT_635_HEIKEN_ASHI_SWING, STRAT_636_HEIKEN_ASHI_EXPANSION,
   STRAT_637_HEIKEN_ASHI_CONTINUE, STRAT_638_HEIKEN_ASHI_VOLATILE, STRAT_639_HEIKEN_ASHI_POSITION,
   STRAT_640_HEIKEN_ASHI_MAJOR,
   STRAT_641_AROON_MICRO, STRAT_642_AROON_FAST, STRAT_643_AROON_SHORT,
   STRAT_644_AROON_INTRADAY, STRAT_645_AROON_SWING, STRAT_646_AROON_EXPANSION,
   STRAT_647_AROON_CONTINUE, STRAT_648_AROON_VOLATILE, STRAT_649_AROON_POSITION,
   STRAT_650_AROON_MAJOR,
   STRAT_651_KST_MICRO, STRAT_652_KST_FAST, STRAT_653_KST_SHORT,
   STRAT_654_KST_INTRADAY, STRAT_655_KST_SWING, STRAT_656_KST_EXPANSION,
   STRAT_657_KST_CONTINUE, STRAT_658_KST_VOLATILE, STRAT_659_KST_POSITION,
   STRAT_660_KST_MAJOR,
   STRAT_661_VORTEX_MICRO, STRAT_662_VORTEX_FAST, STRAT_663_VORTEX_SHORT,
   STRAT_664_VORTEX_INTRADAY, STRAT_665_VORTEX_SWING, STRAT_666_VORTEX_EXPANSION,
   STRAT_667_VORTEX_CONTINUE, STRAT_668_VORTEX_VOLATILE, STRAT_669_VORTEX_POSITION,
   STRAT_670_VORTEX_MAJOR,
   STRAT_671_CONNORS_RSI_MICRO, STRAT_672_CONNORS_RSI_FAST, STRAT_673_CONNORS_RSI_SHORT,
   STRAT_674_CONNORS_RSI_INTRADAY, STRAT_675_CONNORS_RSI_SWING, STRAT_676_CONNORS_RSI_EXPANSION,
   STRAT_677_CONNORS_RSI_CONTINUE, STRAT_678_CONNORS_RSI_VOLATILE, STRAT_679_CONNORS_RSI_POSITION,
   STRAT_680_CONNORS_RSI_MAJOR,
   STRAT_681_VWAP_MICRO, STRAT_682_VWAP_FAST, STRAT_683_VWAP_SHORT,
   STRAT_684_VWAP_INTRADAY, STRAT_685_VWAP_SWING, STRAT_686_VWAP_EXPANSION,
   STRAT_687_VWAP_CONTINUE, STRAT_688_VWAP_VOLATILE, STRAT_689_VWAP_POSITION,
   STRAT_690_VWAP_MAJOR,
   STRAT_691_PIVOT_MICRO, STRAT_692_PIVOT_FAST, STRAT_693_PIVOT_SHORT,
   STRAT_694_PIVOT_INTRADAY, STRAT_695_PIVOT_SWING, STRAT_696_PIVOT_EXPANSION,
   STRAT_697_PIVOT_CONTINUE, STRAT_698_PIVOT_VOLATILE, STRAT_699_PIVOT_POSITION,
   STRAT_700_PIVOT_MAJOR,
   STRAT_701_REG_CHANNEL_MICRO, STRAT_702_REG_CHANNEL_FAST, STRAT_703_REG_CHANNEL_SHORT,
   STRAT_704_REG_CHANNEL_INTRADAY, STRAT_705_REG_CHANNEL_SWING, STRAT_706_REG_CHANNEL_EXPANSION,
   STRAT_707_REG_CHANNEL_CONTINUE, STRAT_708_REG_CHANNEL_VOLATILE, STRAT_709_REG_CHANNEL_POSITION,
   STRAT_710_REG_CHANNEL_MAJOR,
   STRAT_711_MA_ENVELOPE_MICRO, STRAT_712_MA_ENVELOPE_FAST, STRAT_713_MA_ENVELOPE_SHORT,
   STRAT_714_MA_ENVELOPE_INTRADAY, STRAT_715_MA_ENVELOPE_SWING, STRAT_716_MA_ENVELOPE_EXPANSION,
   STRAT_717_MA_ENVELOPE_CONTINUE, STRAT_718_MA_ENVELOPE_VOLATILE, STRAT_719_MA_ENVELOPE_POSITION,
   STRAT_720_MA_ENVELOPE_MAJOR,
   STRAT_721_RSI_DIVERGE_MICRO, STRAT_722_RSI_DIVERGE_FAST, STRAT_723_RSI_DIVERGE_SHORT,
   STRAT_724_RSI_DIVERGE_INTRADAY, STRAT_725_RSI_DIVERGE_SWING, STRAT_726_RSI_DIVERGE_EXPANSION,
   STRAT_727_RSI_DIVERGE_CONTINUE, STRAT_728_RSI_DIVERGE_VOLATILE, STRAT_729_RSI_DIVERGE_POSITION,
   STRAT_730_RSI_DIVERGE_MAJOR,
   STRAT_731_MACD_DIVERGE_MICRO, STRAT_732_MACD_DIVERGE_FAST, STRAT_733_MACD_DIVERGE_SHORT,
   STRAT_734_MACD_DIVERGE_INTRADAY, STRAT_735_MACD_DIVERGE_SWING, STRAT_736_MACD_DIVERGE_EXPANSION,
   STRAT_737_MACD_DIVERGE_CONTINUE, STRAT_738_MACD_DIVERGE_VOLATILE, STRAT_739_MACD_DIVERGE_POSITION,
   STRAT_740_MACD_DIVERGE_MAJOR,
   STRAT_741_CCI_DIVERGE_MICRO, STRAT_742_CCI_DIVERGE_FAST, STRAT_743_CCI_DIVERGE_SHORT,
   STRAT_744_CCI_DIVERGE_INTRADAY, STRAT_745_CCI_DIVERGE_SWING, STRAT_746_CCI_DIVERGE_EXPANSION,
   STRAT_747_CCI_DIVERGE_CONTINUE, STRAT_748_CCI_DIVERGE_VOLATILE, STRAT_749_CCI_DIVERGE_POSITION,
   STRAT_750_CCI_DIVERGE_MAJOR,
   STRAT_751_STOCH_DIVERGE_MICRO, STRAT_752_STOCH_DIVERGE_FAST, STRAT_753_STOCH_DIVERGE_SHORT,
   STRAT_754_STOCH_DIVERGE_INTRADAY, STRAT_755_STOCH_DIVERGE_SWING, STRAT_756_STOCH_DIVERGE_EXPANSION,
   STRAT_757_STOCH_DIVERGE_CONTINUE, STRAT_758_STOCH_DIVERGE_VOLATILE, STRAT_759_STOCH_DIVERGE_POSITION,
   STRAT_760_STOCH_DIVERGE_MAJOR,
   STRAT_761_OBV_DIVERGE_MICRO, STRAT_762_OBV_DIVERGE_FAST, STRAT_763_OBV_DIVERGE_SHORT,
   STRAT_764_OBV_DIVERGE_INTRADAY, STRAT_765_OBV_DIVERGE_SWING, STRAT_766_OBV_DIVERGE_EXPANSION,
   STRAT_767_OBV_DIVERGE_CONTINUE, STRAT_768_OBV_DIVERGE_VOLATILE, STRAT_769_OBV_DIVERGE_POSITION,
   STRAT_770_OBV_DIVERGE_MAJOR,
   STRAT_771_RSI_BANDS_MICRO, STRAT_772_RSI_BANDS_FAST, STRAT_773_RSI_BANDS_SHORT,
   STRAT_774_RSI_BANDS_INTRADAY, STRAT_775_RSI_BANDS_SWING, STRAT_776_RSI_BANDS_EXPANSION,
   STRAT_777_RSI_BANDS_CONTINUE, STRAT_778_RSI_BANDS_VOLATILE, STRAT_779_RSI_BANDS_POSITION,
   STRAT_780_RSI_BANDS_MAJOR,
   STRAT_781_MACD_RSI_MICRO, STRAT_782_MACD_RSI_FAST, STRAT_783_MACD_RSI_SHORT,
   STRAT_784_MACD_RSI_INTRADAY, STRAT_785_MACD_RSI_SWING, STRAT_786_MACD_RSI_EXPANSION,
   STRAT_787_MACD_RSI_CONTINUE, STRAT_788_MACD_RSI_VOLATILE, STRAT_789_MACD_RSI_POSITION,
   STRAT_790_MACD_RSI_MAJOR,
   STRAT_791_ADX_RSI_MICRO, STRAT_792_ADX_RSI_FAST, STRAT_793_ADX_RSI_SHORT,
   STRAT_794_ADX_RSI_INTRADAY, STRAT_795_ADX_RSI_SWING, STRAT_796_ADX_RSI_EXPANSION,
   STRAT_797_ADX_RSI_CONTINUE, STRAT_798_ADX_RSI_VOLATILE, STRAT_799_ADX_RSI_POSITION,
   STRAT_800_ADX_RSI_MAJOR,
   STRAT_801_MA_VOLUME_MICRO, STRAT_802_MA_VOLUME_FAST, STRAT_803_MA_VOLUME_SHORT,
   STRAT_804_MA_VOLUME_INTRADAY, STRAT_805_MA_VOLUME_SWING, STRAT_806_MA_VOLUME_EXPANSION,
   STRAT_807_MA_VOLUME_CONTINUE, STRAT_808_MA_VOLUME_VOLATILE, STRAT_809_MA_VOLUME_POSITION,
   STRAT_810_MA_VOLUME_MAJOR,
   STRAT_811_MA_VOLATILITY_MICRO, STRAT_812_MA_VOLATILITY_FAST, STRAT_813_MA_VOLATILITY_SHORT,
   STRAT_814_MA_VOLATILITY_INTRADAY, STRAT_815_MA_VOLATILITY_SWING, STRAT_816_MA_VOLATILITY_EXPANSION,
   STRAT_817_MA_VOLATILITY_CONTINUE, STRAT_818_MA_VOLATILITY_VOLATILE, STRAT_819_MA_VOLATILITY_POSITION,
   STRAT_820_MA_VOLATILITY_MAJOR,
   STRAT_821_TRIPLE_MA_MICRO, STRAT_822_TRIPLE_MA_FAST, STRAT_823_TRIPLE_MA_SHORT,
   STRAT_824_TRIPLE_MA_INTRADAY, STRAT_825_TRIPLE_MA_SWING, STRAT_826_TRIPLE_MA_EXPANSION,
   STRAT_827_TRIPLE_MA_CONTINUE, STRAT_828_TRIPLE_MA_VOLATILE, STRAT_829_TRIPLE_MA_POSITION,
   STRAT_830_TRIPLE_MA_MAJOR,
   STRAT_831_IMPULSE_MICRO, STRAT_832_IMPULSE_FAST, STRAT_833_IMPULSE_SHORT,
   STRAT_834_IMPULSE_INTRADAY, STRAT_835_IMPULSE_SWING, STRAT_836_IMPULSE_EXPANSION,
   STRAT_837_IMPULSE_CONTINUE, STRAT_838_IMPULSE_VOLATILE, STRAT_839_IMPULSE_POSITION,
   STRAT_840_IMPULSE_MAJOR,
   STRAT_841_BREAKOUT_PULLBACK_MICRO, STRAT_842_BREAKOUT_PULLBACK_FAST, STRAT_843_BREAKOUT_PULLBACK_SHORT,
   STRAT_844_BREAKOUT_PULLBACK_INTRADAY, STRAT_845_BREAKOUT_PULLBACK_SWING, STRAT_846_BREAKOUT_PULLBACK_EXPANSION,
   STRAT_847_BREAKOUT_PULLBACK_CONTINUE, STRAT_848_BREAKOUT_PULLBACK_VOLATILE, STRAT_849_BREAKOUT_PULLBACK_POSITION,
   STRAT_850_BREAKOUT_PULLBACK_MAJOR,
   STRAT_851_TREND_PULLBACK_MICRO, STRAT_852_TREND_PULLBACK_FAST, STRAT_853_TREND_PULLBACK_SHORT,
   STRAT_854_TREND_PULLBACK_INTRADAY, STRAT_855_TREND_PULLBACK_SWING, STRAT_856_TREND_PULLBACK_EXPANSION,
   STRAT_857_TREND_PULLBACK_CONTINUE, STRAT_858_TREND_PULLBACK_VOLATILE, STRAT_859_TREND_PULLBACK_POSITION,
   STRAT_860_TREND_PULLBACK_MAJOR,
   STRAT_861_RSI_MACD_CONFIRM_MICRO, STRAT_862_RSI_MACD_CONFIRM_FAST, STRAT_863_RSI_MACD_CONFIRM_SHORT,
   STRAT_864_RSI_MACD_CONFIRM_INTRADAY, STRAT_865_RSI_MACD_CONFIRM_SWING, STRAT_866_RSI_MACD_CONFIRM_EXPANSION,
   STRAT_867_RSI_MACD_CONFIRM_CONTINUE, STRAT_868_RSI_MACD_CONFIRM_VOLATILE, STRAT_869_RSI_MACD_CONFIRM_POSITION,
   STRAT_870_RSI_MACD_CONFIRM_MAJOR,
   STRAT_871_TREND_FILTER_MICRO, STRAT_872_TREND_FILTER_FAST, STRAT_873_TREND_FILTER_SHORT,
   STRAT_874_TREND_FILTER_INTRADAY, STRAT_875_TREND_FILTER_SWING, STRAT_876_TREND_FILTER_EXPANSION,
   STRAT_877_TREND_FILTER_CONTINUE, STRAT_878_TREND_FILTER_VOLATILE, STRAT_879_TREND_FILTER_POSITION,
   STRAT_880_TREND_FILTER_MAJOR,
   STRAT_881_HARAMI_MICRO, STRAT_882_HARAMI_FAST, STRAT_883_HARAMI_SHORT,
   STRAT_884_HARAMI_INTRADAY, STRAT_885_HARAMI_SWING, STRAT_886_HARAMI_EXPANSION,
   STRAT_887_HARAMI_CONTINUE, STRAT_888_HARAMI_VOLATILE, STRAT_889_HARAMI_POSITION,
   STRAT_890_HARAMI_MAJOR,
   STRAT_891_DOJI_STAR_MICRO, STRAT_892_DOJI_STAR_FAST, STRAT_893_DOJI_STAR_SHORT,
   STRAT_894_DOJI_STAR_INTRADAY, STRAT_895_DOJI_STAR_SWING, STRAT_896_DOJI_STAR_EXPANSION,
   STRAT_897_DOJI_STAR_CONTINUE, STRAT_898_DOJI_STAR_VOLATILE, STRAT_899_DOJI_STAR_POSITION,
   STRAT_900_DOJI_STAR_MAJOR,
   STRAT_901_STAR_MICRO, STRAT_902_STAR_FAST, STRAT_903_STAR_SHORT,
   STRAT_904_STAR_INTRADAY, STRAT_905_STAR_SWING, STRAT_906_STAR_EXPANSION,
   STRAT_907_STAR_CONTINUE, STRAT_908_STAR_VOLATILE, STRAT_909_STAR_POSITION,
   STRAT_910_STAR_MAJOR,
   STRAT_911_SOLDIERS_CROWS_MICRO, STRAT_912_SOLDIERS_CROWS_FAST, STRAT_913_SOLDIERS_CROWS_SHORT,
   STRAT_914_SOLDIERS_CROWS_INTRADAY, STRAT_915_SOLDIERS_CROWS_SWING, STRAT_916_SOLDIERS_CROWS_EXPANSION,
   STRAT_917_SOLDIERS_CROWS_CONTINUE, STRAT_918_SOLDIERS_CROWS_VOLATILE, STRAT_919_SOLDIERS_CROWS_POSITION,
   STRAT_920_SOLDIERS_CROWS_MAJOR,
   STRAT_921_MARUBOZU_MICRO, STRAT_922_MARUBOZU_FAST, STRAT_923_MARUBOZU_SHORT,
   STRAT_924_MARUBOZU_INTRADAY, STRAT_925_MARUBOZU_SWING, STRAT_926_MARUBOZU_EXPANSION,
   STRAT_927_MARUBOZU_CONTINUE, STRAT_928_MARUBOZU_VOLATILE, STRAT_929_MARUBOZU_POSITION,
   STRAT_930_MARUBOZU_MAJOR,
   STRAT_931_DOUBLE_TOP_BOTTOM_MICRO, STRAT_932_DOUBLE_TOP_BOTTOM_FAST, STRAT_933_DOUBLE_TOP_BOTTOM_SHORT,
   STRAT_934_DOUBLE_TOP_BOTTOM_INTRADAY, STRAT_935_DOUBLE_TOP_BOTTOM_SWING, STRAT_936_DOUBLE_TOP_BOTTOM_EXPANSION,
   STRAT_937_DOUBLE_TOP_BOTTOM_CONTINUE, STRAT_938_DOUBLE_TOP_BOTTOM_VOLATILE, STRAT_939_DOUBLE_TOP_BOTTOM_POSITION,
   STRAT_940_DOUBLE_TOP_BOTTOM_MAJOR,
   STRAT_941_FALSE_BREAK_MICRO, STRAT_942_FALSE_BREAK_FAST, STRAT_943_FALSE_BREAK_SHORT,
   STRAT_944_FALSE_BREAK_INTRADAY, STRAT_945_FALSE_BREAK_SWING, STRAT_946_FALSE_BREAK_EXPANSION,
   STRAT_947_FALSE_BREAK_CONTINUE, STRAT_948_FALSE_BREAK_VOLATILE, STRAT_949_FALSE_BREAK_POSITION,
   STRAT_950_FALSE_BREAK_MAJOR,
   STRAT_951_EXHAUSTION_MICRO, STRAT_952_EXHAUSTION_FAST, STRAT_953_EXHAUSTION_SHORT,
   STRAT_954_EXHAUSTION_INTRADAY, STRAT_955_EXHAUSTION_SWING, STRAT_956_EXHAUSTION_EXPANSION,
   STRAT_957_EXHAUSTION_CONTINUE, STRAT_958_EXHAUSTION_VOLATILE, STRAT_959_EXHAUSTION_POSITION,
   STRAT_960_EXHAUSTION_MAJOR
};

// ==================== INIT ====================
int OnInit()
{
   return INIT_SUCCEEDED;
}

// ==================== TICK - THE MAIN LOOP (FIXED) ====================
void OnTick()
{
   // ▼ KEY FIX #1: Check if new bar arrived (once per bar only)
   datetime currentBar = iTime(Symbol(), Period(), 0);
   if(currentBar == lastBarProcessed)
      return;  // Already processed this bar
   
   lastBarProcessed = currentBar;

   // Spawn new run every N minutes
   static datetime lastSpawnTime = 0;
   if(TimeCurrent() - lastSpawnTime >= spawnIntervalMinutes * 60)
   {
      SpawnNewRun();
      lastSpawnTime = TimeCurrent();
   }

   // ▼ KEY FIX #2: Process ALL active runs for this bar
   ProcessAllActiveRuns();
}

// ==================== SPAWN NEW RUN ====================
void SpawnNewRun()
{
   if(totalRuns >= 10000)
   {
      Print("Maximum runs reached (10000)");
      return;
   }

   activeRuns[totalRuns].startTime = TimeCurrent();
   activeRuns[totalRuns].lastProcessedBar = 0;  // ← Initialize to 0
   activeRuns[totalRuns].tradeCount = 0;
   activeRuns[totalRuns].signalCount = 0;
   activeRuns[totalRuns].startBalance = startingBalance;
   activeRuns[totalRuns].currentBalance = startingBalance;
   activeRuns[totalRuns].maxProfit = 0;
   activeRuns[totalRuns].maxDrawdown = 0;
   activeRuns[totalRuns].isActive = true;
   activeRuns[totalRuns].status = "ACTIVE";

   Print("Run #", totalRuns, " spawned at ", TimeToString(activeRuns[totalRuns].startTime));
   totalRuns++;
}

// ==================== PROCESS ALL ACTIVE RUNS (THE FIX) ====================
void ProcessAllActiveRuns()
{
   datetime currentBarTime = iTime(Symbol(), Period(), 0);

   // Loop through ALL active runs
   for(int i = 0; i < totalRuns; i++)
   {
      if(!activeRuns[i].isActive)
         continue;  // Skip completed runs

      // ▼ KEY FIX #3: Skip if this run hasn't started yet
      if(currentBarTime < activeRuns[i].startTime)
         continue;

      // ▼ KEY FIX #4: Only process bar once per run
      if(activeRuns[i].lastProcessedBar == currentBarTime)
         continue;

      // NOW process this run for current bar
      ProcessSingleRun(i);

      // Mark this bar as processed for this run
      activeRuns[i].lastProcessedBar = currentBarTime;
   }
}

// ==================== PROCESS SINGLE RUN ====================
void ProcessSingleRun(int runIndex)
{
   RunState &run = activeRuns[runIndex];

   // Get signal from selected strategy
   int signal = GetSignal(selectedStrategy);

   if(signal != 0)
   {
      run.signalCount++;

      // Execute trade
      if((signal == 1 && selectedStrategy != SIGNAL_SELL_ONLY) || 
         (signal == -1 && selectedStrategy != SIGNAL_BUY_ONLY))
      {
         ExecuteTrade(signal, runIndex);
         run.tradeCount++;
      }
   }

   // Update equity metrics
   UpdateRunMetrics(runIndex);

   // Check termination conditions
   CheckTermination(runIndex);
}

// ==================== GET SIGNAL ====================
int GetSignal(int strategyID)
{
   // Example: ADX_RSI_POSITION (799)
   double adx = iADX(Symbol(), Period(), 14, PRICE_CLOSE, 0);
   double rsi = iRSI(Symbol(), Period(), 14, PRICE_CLOSE, 0);

   // If ADX strong and RSI oversold = BUY
   if(adx > 25 && rsi < 30)
      return reverseSignals ? -1 : 1;

   // If ADX strong and RSI overbought = SELL
   if(adx > 25 && rsi > 70)
      return reverseSignals ? 1 : -1;

   return 0;  // No signal
}

// ==================== EXECUTE TRADE ====================
void ExecuteTrade(int signal, int runIndex)
{
   if(!oneTradePerBar)
      return;  // Dummy for now

   // Simulate trade
   Print("Run #", runIndex, " | Signal: ", (signal > 0 ? "BUY" : "SELL"), 
         " | Price: ", SymbolInfoDouble(Symbol(), SYMBOL_ASK));
}

// ==================== UPDATE RUN METRICS ====================
void UpdateRunMetrics(int runIndex)
{
   RunState &run = activeRuns[runIndex];

   // Simple P&L calculation (based on trade count for simulation)
   double pnl = (run.tradeCount * 50.0) - (run.tradeCount * 25.0);  // Simplified
   run.currentBalance = run.startBalance + pnl;

   // Track max profit
   if(pnl > run.maxProfit)
      run.maxProfit = pnl;

   // Track max drawdown
   if(pnl < 0 && MathAbs(pnl) > run.maxDrawdown)
      run.maxDrawdown = MathAbs(pnl);
}

// ==================== CHECK TERMINATION ====================
void CheckTermination(int runIndex)
{
   RunState &run = activeRuns[runIndex];

   // Hit profit target?
   if(run.currentBalance >= run.startBalance + profitTarget)
   {
      run.isActive = false;
      run.status = "PASSED";
      Print("Run #", runIndex, " PASSED | Profit: $", DoubleToString(run.currentBalance - run.startBalance, 2));
      return;
   }

   // Hit loss limit?
   if(run.maxDrawdown >= maxTotalDrawdown)
   {
      run.isActive = false;
      run.status = "BLOWN";
      Print("Run #", runIndex, " BLOWN | Loss: $", DoubleToString(run.maxDrawdown, 2));
      return;
   }
}

// ==================== DEINIT ====================
void OnDeinit(const int reason)
{
   Print("=== FINAL REPORT ===");
   int passed = 0, blown = 0, active = 0;
   
   for(int i = 0; i < totalRuns; i++)
   {
      if(activeRuns[i].status == "PASSED") passed++;
      else if(activeRuns[i].status == "BLOWN") blown++;
      else active++;
      
      Print("Run ", i, " | Status: ", activeRuns[i].status, 
            " | Trades: ", activeRuns[i].tradeCount, 
            " | Signals: ", activeRuns[i].signalCount,
            " | P/L: $", DoubleToString(activeRuns[i].currentBalance - activeRuns[i].startBalance, 2));
   }
   
   Print("Total: ", totalRuns, " | Passed: ", passed, " | Blown: ", blown, " | Active: ", active);
}
